// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdcmmkkdgbdubskmhwit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkY21ta2tkZ2JkdWJza21od2l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MjAyMDksImV4cCI6MjA2NDI5NjIwOX0.ru0EexYvIt56EH7CRdBLDmvHXf0RWJo9deyvPd4dBm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);